@DOMAIN = http://localhost:3000

### Mutation createUser
POST {{DOMAIN}}/graphql

{
	"query": "mutation { createUser( input: { name: \"Alice\", email: \"alice@example.com\", age: 25 } ) { id name email age } }"
}

### Query users
POST {{DOMAIN}}/graphql

{
	"query": "{ users { id name email age } }"
}
