@DOMAIN = http://localhost:3000
@ID = c0ad5cb3-17a6-4a34-b196-050d1530370e

### Mutation createUser
POST {{DOMAIN}}/graphql

{
	"query": "mutation { createUser( input: { name: \"Alice\", email: \"alice@example.com\", age: 25 } ) { id name email age } }"
}

### Query users
POST {{DOMAIN}}/graphql

{
	"query": "{ users { id name email age } }"
}

### Query user
POST {{DOMAIN}}/graphql

{
	"query": "{ user(id: \"{{ID}}\") { id name email age } }"
}

### Mutation updateUser
POST {{DOMAIN}}/graphql

{
	"query": "mutation { updateUser( input: { id: \"{{ID}}\", name: \"Alice\", email: \"alice2@gmail.com\", age: 26 } ) { id name email age } }"
}

### Mutation updateUser
POST {{DOMAIN}}/graphql

{
	"query": "mutation { updateUser( input: { id: \"{{ID}}\", name: \"Alice\", email: \"alice@gmail.com\", age: 25 } ) { id name email age } }"
}

### Mutation removeUser
POST {{DOMAIN}}/graphql

{
	"query": "mutation { removeUser(id: \"{{ID}}\") { id name } }"
}

