@DOMAIN = http://localhost:3000

### Mutation createUser
POST {{DOMAIN}}/graphql

{
	"query": "mutation { createUser( input: { name: \"Alice\", email: \"alice@example.com\", age: 25 } ) { id name email age } }"
}

### Query users
POST {{DOMAIN}}/graphql

{
	"query": "{ users { id name email age } }"
}

### Query user
POST {{DOMAIN}}/graphql

{
	"query": "{ user(id: 1) { id name email age } }"
}

### Mutation updateUser
POST {{DOMAIN}}/graphql

{
	"query": "mutation { updateUser( input: { id: 1, name: \"Alice\", email: \"alice2@gmail.com\", age: 26 } ) { id name email age } }"
}

### Mutation updateUser
POST {{DOMAIN}}/graphql

{
	"query": "mutation { updateUser( input: { id: 1, name: \"Alice\", email: \"alice@gmail.com\", age: 25 } ) { id name email age } }"
}

### Mutation removeUser
POST {{DOMAIN}}/graphql

{
	"query": "mutation { removeUser(id: 1) { id name } }"
}

